[[redirects]]
  from = "https://subtle-yeot-c5c491.netlify.app/lives.json"
  to = "https://gitee.com/sierpin/lives/raw/main/lives.json"
  force = true
[[redirects]]
  from = "https://subtle-yeot-c5c491.netlify.app/a.json"
  to = "https://gitee.com/sierpin/lives/raw/main/a.json"
  force = true