[[redirects]]
  from = "https://subtle-yeot-c5c491.netlify.app/1lives.json"
  to = "https://raw.gitmirror.com/zyzyzy523/api/main/lives.json"
  force = true
[[redirects]]
  from = "https://subtle-yeot-c5c491.netlify.app/1a.json"
  to = "https://raw.gitmirror.com/zyzyzy523/api/main/a.json"
  force = true