aj:
  captcha:
    cache-type: redis
    water-mark: admin-server

logging:
  level:
    com:
      admin: ${LOG_LEVEL:debug}
    root: info

mysql:
  db-name: data

server:
  port: 9000
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWD}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://dev.ip.local:${DB_PORT}/${mysql.db-name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&autoReconnect=true
    username: ${DB_USER}
  data:
    redis:
      host: dev.ip.local
      password: ${REDIS_PASSWD}
      port: 32578
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true